name: mdigits
description: Digit span task that can be added to flutter apps
version: 0.0.1

publish_to: 'none' 

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  stimuli:
    path: stimuli
  file_picker: ^5.2.4
  shared_preferences: ^2.0.15
  permission_handler: ^10.2.0
  get: ^4.6.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  test: ^1.21.1

flutter:

  uses-material-design: true

  # assets:
